// <auto-generated />
namespace TallerApis.Apis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CambioEstructuraPublicacion3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioEstructuraPublicacion3));
        
        string IMigrationMetadata.Id
        {
            get { return "201810130407403_CambioEstructuraPublicacion3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
